version: '3.8'

services:
  backend:
    container_name: application
    image: application
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/api/usr/app
    links:
      - postgres_db
    depends_on:
      - postgres_db
  postgres_db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=barbershop-db
  
volumes:
  postgresql:
  postgresql_data: